root = "/var/vcap/data/containerd/root"
state = "/var/vcap/data/containerd/state"
subreaper = true
oom_score = -999
disabled_plugins = [
  "aufs",
  "overlayfs",
  "zfs",
  "walking",
  "scheduler",
  "content-service",
  "diff-service",
  "images-service",
  "namespaces-service",
  "snapshots-service",
  "content",
  "diff",
  "events",
  "images",
  "namespaces",
  "snapshots",
  "version",
  "cri"
]

[grpc]
address = "/var/vcap/data/containerd/sockets/containerd.sock"
uid = 4294967294
gid = 4294967294

[debug]
address = "/var/vcap/data/containerd/sockets/debug.sock"
uid = 4294967294
gid = 4294967294
level = "debug"

[plugins]
  [plugins.linux]
    runtime_root = "/var/run/user/4294967294/runc"
